title: Felipe Lisboa Malaquias
logo: /assets/img/eu.jpg
email: flisboa@telecom-paris.fr
description: Welcome to my personal page :)
remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/felipelisboa-ml
